experiment:
  name: evidential_function_testing
  model_runs: 10
  seed: 42

  data:
    function: # List [function, noise_function]
      #- [f_cubic_rocket_1_feat_range, sigma_cubic_rocket_1_feat_range]
      - [f_linear_1_feature, sigma_constant_1_feature]

    train_data:
      interval: 
        - [-4.0, 4.0] 
        # - [[-2.0, -0.5], [0.5, 2.0]]
      n_instances: 
        #- 10
        # - 100
        - 100
        # - 10000
        #- 100000
      n_repeats:
        - 1
        # - 2
        # - 3
        # - 4
        # - 5
        # - 6
        # - 7
        # - 8
        # - 9
        # - 10
        #- 10
        #- 30
    test_data:
      interval: 
        - [-7.0, 7.0]
      grid_length: 
        - 1000
      #test_points:
      #  - [-1000, -900, -800, -700, -600, -500, -400, -300, -200, -100, 0, 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000]


  models:
    - base_model:
        hidden_features: [64, 64]
        activations: [relu, relu]
        lr: 0.001
        epochs: 200
        batch_size: 32
        weight_decay: 0
        p_drop: 0
        shuffle: True
        device: cpu
        target_dim: 1

    # - mcdropout:
    #     p_drop: 0.1
    #     lr: 0.001
    #     batch_size: 32
    #     epochs: 300
    #     n_mc_samples: 250

    - evidential:
        coeff: 0.01
        lr: 0.0005
        batch_size: 100
        epochs: 500

    # - bbb:
    #     prior_mean: 0.0
    #     prior_sigma: 0.5
    #     kl_beta: 0.3
    #     n_mc_samples: 250
    #     mu_init_mean: 0
    #     mu_init_std: 0.1
    #     rho_init: -5.0
    #     lr: 0.001
    #     batch_size: 32
    #     epochs: 300
      
    # - ensemble:
    #     weight_decay: 0.001
    #     n_members: 5
    #     lr: 0.0005
    #     epochs: 200
    #     batch_size: 64
