experiment:
  name: complex_function_v2
  model_runs: 1
  seed: 42

  data:
    function: # List [function, noise_function]
      - [f_linear_1_feature_complex_v2, sigma_linear_1_feature_complex_v2]

    train_data:
      interval: 
        - [-2.0, 2.0]
        # - [[-2.0, -0.5], [0.5, 2.0]]
      n_instances: 
        #- 10
        # - 100
        - 1000
        #- 10000
        #- 100000
      n_repeats:
        - 1

    test_data:
      interval: 
        - [-4.0, 4.0]
      grid_length: 
        - 100
      #test_points:
      #  - [-1000, -900, -800, -700, -600, -500, -400, -300, -200, -100, 0, 100, 200, 300, 400, 500, 600, 700, 800, 900, 1000]


  models:
    - base_model:
        hidden_features: [64, 64]
        activations: [relu, relu]
        lr: 0.0005
        epochs: 500
        batch_size: 100
        weight_decay: 0
        p_drop: 0
        shuffle: True
        device: cpu
        target_dim: 1

    - mcdropout:
        p_drop: 0.1
        n_mc_samples: 100
        length_scale: 1.0
        tau: 1.0

    - evidential:
        coeff: 0.01

    - bbb:
        prior_sigma1: 1.0
        prior_sigma2: 0.1
        prior_pi: 0.5
        kl_beta: 1.0
        n_mc_samples: 100
        mu_init_mean: 0
        mu_init_std: 0.02
        rho_init: -5.0
      
    - ensemble:
        weight_decay: 0.001
        n_members: 5
