experiment:
  name: exp1_n_unique
  model_runs: 5
  seed: 42

  data:
    function: # List [function, noise_function]
      - [f_cosine_hc2_1_feat, sigma_cubic_hc2_1_feat]

    train_data:
      interval: 
        - [-4.0, 4.0] 
      n_instances: 
        - 40
        - 200
        - 1000
        - 5000
        - 25000
        - 100000
      n_repeats:
        - 0
    test_data:
      interval: 
        - [-6.0, 6.0]
      grid_length: 
        - 1000
      add_points:
        - [-1e6, -1e5, -1e4, -1e3, -1e2, -1e1, 1e1, 1e2, -1e3, 1e4, 1e5, 1e6]

  models:
    - base_model:
        # fixed hps
        hidden_features: [64, 64]
        activations: [relu, relu]
        weight_decay: 0.0
        p_drop: 0.0
        shuffle: True
        device: cpu
        target_dim: 1

    - mcdropout:
        # fixed hps
        n_mc_samples: 300
        # tuned hps
        p_drop: 0.05
        weight_decay: 0.0005
        lr: 0.001
        epochs: 200
        batch_size: 64

    - evidential:
        # tuned hps
        coeff: 0.005
        lr: 0.001
        epochs: 100
        batch_size: 32

    - bbb:
        # fixed hps
        mu_init_mean: 0.0
        prior_mean: 0.0
        n_mc_samples: 300
        # tuned hps
        prior_sigma: 1.0
        kl_beta: 0.3
        mu_init_std: 0.1
        rho_init: -5.0
        lr: 0.001
        epochs: 100
        batch_size: 32
      
    - ensemble:
        # fixed hps
        n_members: 5
        # tuned hps
        weight_decay: 0.0001
        lr: 0.001
        epochs: 200
        batch_size: 32
