experiment:
  name: two_feat_hc2
  model_runs: 5
  seed: 42

  data:
    function: # List [function, noise_function]

    # # # High correlation functions
      # - [
      #     [f_sinusoidal_hc2_1_feat, sigma_cubic_hc2_1_feat],
      #     [f_cosine_hc1_1_feat, sigma_cubic_hc1_1_feat],
      #     [f_cosine_hydra_1_feat, sigma_cubic_hydra_1_feat],
      #     [f_cosine_multi_r_1_feat, sigma_cubic_multi_r_1_feat],
      #     [f_sinusoidal_stc_1_feat, sigma_cubic_stc_1_feat],
      #     [f_cosine_ts_chief_1_feat, sigma_cubic_ts_chief_1_feat],
      #   ]

    # # # Low correlation functions
      # - [
      #     [f_sinusoidal_hc2_1_feat, sigma_cubic_hc2_1_feat],
      #     [f_cosine_tsfresh_1_feat, sigma_cubic_tsfresh_1_feat],
      #     [f_quadratic_cboss_1_feat, sigma_quadratic_cboss_1_feat],
      #     [f_cubic_mini_r_1_feat, sigma_cubic_mini_r_1_feat],
      #     [f_quadratic_pf_1_feat, sigma_cubic_pf_1_feat],
      #     [f_cosine_shapedtw_1_feat, sigma_quadratic_shapedtw_1_feat],
      #   ]



      #- [f_sinusoidal_hc2_1_feat, sigma_cubic_hc2_1_feat]
      - [f_quadratic_hc2_2_feat, sigma_quadratic_hc2_2_feat]

    train_data:
      interval: 
        - [-4.0, 4.0] 
        # - [[-4.0, -1.0], [1.0, 4.0]]
      n_instances: 
        - 40
        #- 200
        #- 1000
        #- 5000
        - 25000
        #- 100000
      n_repeats:
        - 0
        # - 1
        # - 2
        # - 3
        # - 4
        # - 5
        # - 6
        # - 7
        # - 8
        # - 9
        # - 10
        # - 11
        # - 12
        # - 13
        # - 14
        # - 15
        # - 16
        # - 17
        # - 18
        # - 19
        # - 20
        # - 21
        # - 22
        # - 23
        # - 24
        # - 25
        # - 26
        # - 27
        # - 28
        # - 29
        # - 30
    test_data:
      interval: 
        - [-6.0, 6.0]
      grid_length: 
        - 100
      add_points:
        - [-1e6, -1e5, -1e4, -1e3, -1e2, -1e1, 1e1, 1e2, -1e3, 1e4, 1e5, 1e6]

  models:
    - base_model:
        # fixed hps
        hidden_features: [64, 64]
        activations: [relu, relu]
        weight_decay: 0.0
        p_drop: 0.0
        shuffle: True
        device: cpu
        target_dim: 1

    - mcdropout:
        # fixed hps
        n_mc_samples: 300
        # tuned hps
        p_drop: 0.05
        weight_decay: 0.0001
        lr: 0.01
        epochs: 100
        batch_size: 32

    - evidential:
        # tuned hps
        coeff: 0.005
        lr: 0.01
        epochs: 200
        batch_size: 32

    - bbb:
        # fixed hps
        mu_init_mean: 0.0
        prior_mean: 0.0
        n_mc_samples: 300
        # tuned hps
        prior_sigma: 0.5
        kl_beta: 0.3
        mu_init_std: 0.1
        rho_init: -5.0
        lr: 0.001
        epochs: 100
        batch_size: 32
      
    - ensemble:
        # fixed hps
        n_members: 5
        # tuned hps
        weight_decay: 0.0001
        lr: 0.001
        epochs: 200
        batch_size: 32
